/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['intro'],
    },
  ],
  networkBar: [{
    type: 'category',
    label: '计算机网络',
    items:   ['network/计算机网络-1.概述', 'network/计算机网络-2.物理层', 'network/计算机网络-3.数据链路层', 'network/计算机网络-6.应用层']
  }],
};

module.exports = sidebars;
