/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['intro'],
    },
  ],
  networkBar: [{
    type: 'category',
    label: '计算机网络',
    items:   [
        'network/计算机网络-1.概述',
      'network/计算机网络-2.物理层',
      'network/计算机网络-3.数据链路层',
      'network/计算机网络-4.网络层',
      'network/计算机网络-5.传输层',
      'network/计算机网络-6.应用层'
    ]
  }],
  dataStructuresBar: [{
    type: 'category',
    label:'数据结构',
    items: [
        'data-structures/数据结构-数组',
        'data-structures/数据结构-栈',
        'data-structures/数据结构-队列',
        'data-structures/数据结构-链表',
        'data-structures/数据结构-树',
        'data-structures/数据结构-散列表',
        'data-structures/数据结构-堆',
        'data-structures/数据结构-图',
    ]
  }],
    webglBar: [{
      type: "category",
        label: "webgl",
        items: [
            "webgl/webgl"
        ]
    }],
    reactBar:[{
        type: 'category',
        label:'react',
        items: [
            'react/状态管理',
        ]
    }],
    frontEndEngineeringBar:[{
        type: 'category',
        label:'工程化',
        items: [
            'front-end-engineering/包管理工具',
        ]
    }],
    browserBar: [{
      type: 'category',
        label:'浏览器相关',
        items: [
            'browser/浏览器架构',
            'browser/浏览器缓存',
            'browser/浏览器事件机制',
        ]
    }],
    handwriteBar: [{
      type: 'category',
        label:'手写系列',
        items: [
            'handwrite/call',
            'handwrite/apply',
            'handwrite/bind',
            'handwrite/new',
            'handwrite/curry',
            'handwrite/throttle',
            'handwrite/debounce',
            'handwrite/async-pool',
            'handwrite/lru-cache',
            'handwrite/deep-clone',
        ],
    }],
  operatingSystemBar: [{
    type: 'category',
    label:'操作系统',
    items: [
        {
          type: 'category',
          label: '1.概述',
          items: [
              'operating-system/操作系统的基本概念',
              'operating-system/操作系统的发展和分类',
              'operating-system/操作系统的运行机制和体系结构',
          ]
        },
      {
        type: 'category',
        label: '2.进程管理',
        items: [
            'operating-system/进程与线程',
            'operating-system/处理机的调度',
            'operating-system/进程的同步与互斥',
            'operating-system/死锁',
        ]
      },
      {
        type: 'category',
        label: '3.内存管理',
        items: [
            'operating-system/内存管理的概念',
            'operating-system/虚拟内存管理',
        ]
      },
      {
        type: 'category',
        label: '4.文件管理',
        items: [
            'operating-system/文件系统',
            'operating-system/磁盘组织与管理',
        ]
      },
      {
        type: 'category',
        label: '5.I/O管理',
        items: [
            'operating-system/I-O管理概述',
            'operating-system/I-O核心子系统',
        ]
      },
      // 'operating-system/操作系统-1.概述',
      // 'operating-system/操作系统-2.进程管理',
      // 'operating-system/操作系统-3.内存管理',
    ]
  }],
};

module.exports = sidebars;
