/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['intro'],
    },
  ],
  networkBar: [{
    type: 'category',
    label: '计算机网络',
    items:   [
        'network/计算机网络-1.概述',
      'network/计算机网络-2.物理层',
      'network/计算机网络-3.数据链路层',
      'network/计算机网络-4.网络层',
      'network/计算机网络-5.传输层',
      'network/计算机网络-6.应用层'
    ]
  }],
  dataStructuresBar: [{
    type: 'category',
    label:'数据结构',
    items: [
        'data-structures/数据结构-1.链表'
    ]
  }],
  operatingSystemBar: [{
    type: 'category',
    label:'操作系统',
    items: [
      'operating-system/操作系统-1.概述',
      'operating-system/操作系统-2.进程管理',
      'operating-system/操作系统-3.内存管理',
    ]
  }],
};

module.exports = sidebars;
