name: deploy to tencent
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      - name: Trust My Directory
        run: git config --global --add safe.directory /github/workspace
      # 下载 git submodule
#      - uses: srt32/git-actions@v0.0.3
#        with:
#          args: git submodule update --init --recursive
      # 使用 node:16
      - name: use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      # Deploy
      - name: Deploy tencentyun
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: "root"
          TARGET: ${{ secrets.REMOTE_TARGET }}
